### ISSUE TITLE
Cursor on buttons

### ISSUE THREAD

**Issue by DanceParty** [micah5/PSone.css#1]
Not sure if intended, but should the cursor change to a pointer when hovering over button? If so, I can PR for it, just wanted to see what intended behavior is!

**Comment by micah5** [comment]
Oh yeah, you're right, oops! I didn't even notice that, you have a good eye for detail. It's not the intended behaviour :)

**Comment by DanceParty** [comment]
Awesome, I'll try and submit a PR tomorrow :)

**Comment by DanceParty** [comment]
@98mprice I believe it should be good!

**Comment by micah5** [comment]
@KeevanDance Thank you! Works beautifully :)
