### ISSUE TITLE
[Feature Request] Progress indeterminate

### ISSUE THREAD

**Issue by guastallaigor** [micah5/PSone.css#3]
I think it would look cool for the progress have an indeterminate CSS animation, kind of like [this](https://vuetifyjs.com/en/components/progress#example-linear-indeterminate).

Not sure if you like this kind of feature in your CSS framework, so if you don't that's fine :)

**Comment by micah5** [comment]
Wow, very cool! Thank you @guastallaigor, that's an awesome addition :)
