### ISSUE TITLE
[Question] New Features

### ISSUE THREAD

**Issue by guastallaigor** [micah5/PSone.css#5]
I would like to know where are you getting the ideas and design/style for your components. I want to try develop basic components that are missing here such as checkboxes, tables, icons, etc, but I'm not sure which is the correct design/style for each of those components. 

Can you point me to the right direction? :)

**Comment by micah5** [comment]
Hey there! Thanks for your help with the development of this library, I really appreciate it.

I took all my ideas for the style from various PS1 games:
- The buttons come from the Tekken 3 menu screen
- The boxes are from FF7 battle dialogs, and the input from FF7 name input screen
- The progress bar from MGS1 life bars
- The radio button is from the PS1 menu card screen

Any PS1 game is fair game though- but it doesn't have to be entirely faithful to the original source. As long as it looks like it's from that era & fits in with the rest of the framework it's all good :)

Thanks again!

**Comment by guastallaigor** [comment]
No problem, I'm still learning so don't expect much :smile: 

I will do some research because I've played mostly SNES in my day and very very little PS1, so I don't know the games but if I found something good I will tell you and try to develop.

Thank you.

**Comment by micah5** [comment]
Awesome, I look forward to it! Thanks :)

**Comment by guastallaigor** [comment]
I will close this now and open new ones when I have some ideas if that's ok.
