### ISSUE TITLE
[Feature Request] PSOne controller buttons

### ISSUE THREAD

**Issue by guastallaigor** [micah5/PSone.css#6]
Add icons or buttons to all PSOne controller buttons, made with pure CSS, no images if possible :)

**Comment by guastallaigor** [comment]
For the arrows I made a first draft:

![image](https://user-images.githubusercontent.com/22016005/49617249-f4138580-f99a-11e8-82f9-f4977dddb70a.png)

But I could not make the `box-shadow` to work on top of everything, so for now I removed, and there's a margin issue that I will try to fix.

I'm using this as example:

![image](https://user-images.githubusercontent.com/22016005/49617290-2b823200-f99b-11e8-841d-94c7a3b0b4db.png)

**Comment by micah5** [comment]
Ah I see. The buttons look really good though, including the arrows. You can submit a pull request for them and I'll see what I can do to get `box-shadow` working. Good work, thanks!

**Comment by micah5** [comment]
![](https://i.imgur.com/pZyRERg.png)

I updated the controller buttons to look more like that example, what do you think?

**Comment by guastallaigor** [comment]
> Ah I see. The buttons look really good though, including the arrows. You can submit a pull request for them and I'll see what I can do to get `box-shadow` working. Good work, thanks!

I will do that when I have some more free time. Thank you for your help, I really appreciate it!



> ![](https://camo.githubusercontent.com/0326021ec20e996b6c791bfd1a0343cd7852b042/68747470733a2f2f692e696d6775722e636f6d2f705a79524552672e706e67)
> 
> I updated the controller buttons to look more like that example, what do you think?

Awesome, it looks a lot better now!

**Comment by guastallaigor** [comment]
Just made two PR's but neither of them is finished. But still, if/when you can, check them out and let me know what do you think about the appearance of it and the code itself. If you have any suggestions or ways to help, please let me know.

Cheers.

**Comment by micah5** [comment]
Thank you! I'll try to have a proper look either today or tomorrow, but they both look great from what I've seen in the screenshots. Great stuff

**Comment by guastallaigor** [comment]
All controller buttons were merged.
